config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

   get 'get-product-list' => 'products#get_product_list'

    resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

	mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  end

  def new
  	@product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
    	redirect_to @product
    else
    	render 'new'
    end
  end

  def show
  	@product = Product.find(params[:id])
  end

  def get_product_list
    product_list = []
    products = Product.all
    if products.present?
      products.each do |product|
        url = product.image.thumb.url
        product_list << product.attributes.merge(image_path: url)
      end
    end
    render json: product_list
  end
 
  private
    def product_params
      params.require(:product).permit(:name, :description, :image, :price)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a ng-click='clearCache()' class="navbar-brand" href="/products">Products</a>
      <%#= link_to 'Products', root_path, class: 'navbar-brand' %>
      <%= link_to 'Products', new_product_path, class: 'navbar-brand pull-right' %>
      
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="gemStore">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Store Shop" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Store Shop" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body ng-controller="storeController as store">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |f| %>
  <%#= f.error_messages %>
  <%#= f.hidden_field :gallery_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>


  <p>
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </p>

  <p>
    <%= f.file_field :image %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/products/index.html.erb
<br/><br/>
<div ng-controller="storeController">
  <%#=link_to "Add Product", new_product_path %>
	<div class="list-group">
	  <!--  Product Container  -->
	  <div class="list-group-item" ng-repeat="product in products">
	    <h3>{{product.name}} <em class="pull-right">{{product.price | currency}}</em></h3>

	    <!-- Image Gallery  -->
	    <!-- <product-gallery></product-gallery> -->
	    <div ng-show="product.image">
		    <div class="col-xs-2 col-md-2 thumbnail">
				  <div class="img-wrap">
				    <img ng-src="{{product.image_path}}" />
				  </div>
				  <ul class="img-thumbnails clearfix">
				    <li class="small-image pull-left thumbnail" ng-repeat="image in product.images">
				      <img ng-src="{{image}}" />
				    </li>
				  </ul>
				</div>
			</div>

	    <!-- Product Tabs  -->
	    <!-- <product-tabs></product-tabs> -->

	    <!-- Tabs Go Here -->
	    <div ng-controller="productTabs as tab">
				<section>
				  <ul class="nav nav-pills">
				    <li ng-class="{ active:isSet(1) }">
				      <a href ng-click="setTab(1)">Description</a>
				    </li>
				<!--     <li ng-class="{ active:isSet(2) }">
				      <a href ng-click="setTab(2)">Specs</a>
				    </li> -->
				    <li ng-class="{ active:isSet(3) }">
				      <a href ng-click="setTab(3)">Reviews</a>
				    </li>
				  </ul>

           <!--  Spec Tab's Content  -->
				  <!-- <div product-specs ng-show="isSet(2)"></div> -->

				  <!--  Review Tab's Content  -->
				  <product-reviews ng-show="isSet(3)"></product-reviews>
				  
				  <!--  Description Tab's Content  -->
				  <div product-description ng-show="isSet(1)" ></product-description>


				</section>
			</div>

	  </div>
	</div>
</div>

app/views/products/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<br/><br/>

<p>
Name:  <%= @product.name %> 
</p>

<p>
Description:  <%= @product.description %> 
</p>

<%= image_tag @product.image_url.to_s %>